import type { Project } from "./projectTypes";

export const projects: Project[] = [
  {
    id: "clay-beats",
    title: "Clay Beats",
    source: "educational",
    categories: ["game"],   
    featured: false,
  },
  {
    id: "floor-after-floor",
    title: "Floor After Floor",
    source: "educational",
    categories: ["game"],   
    featured: true,
  },
  {
    id: "frog-app",
    title: "Frog App",
    source: "educational",
    categories: ["software"],   
    featured: false,
  },
  {
    id: "gaming-yt",
    title: "Gaming, Gaming, & More Gaming",
    source: "personal",
    categories: ["content"],   
    featured: false,
  },
  {
    id: "greek-game",
    title: "Greek Game",
    source: "educational",
    categories: ["game"],   
    featured: false,
  },
  {
    id: "lms",
    title: "Learning Management System",
    source: "educational",
    categories: ["database"],   
    featured: false,
  },
  {
    id: "murphys-game-room",
    title: "Murphy's Game Room",
    source: "personal",
    categories: ["webdesign"],   
    featured: true,
  },
  {
    id: "netsuite-migration",
    title: "Netsuite Migration",
    source: "cswork",
    categories: ["migration", "webdev"],
    featured: false,
  },
  {
    id: "portfolio",
    title: "Portfolio Website",
    source: "personal",
    categories: ["webdev", "webdesign"],
    featured: false,
  },
  {
    id: "return-home",
    title: "Return Home",
    source: "educational",
    categories: ["vr"],
    featured: false,
  },
  {
    id: "reyna-murphy-adventures",
    title: "Reyna Murphy Adventures Photography Site",
    source: "personal",
    categories: ["webdev", "webdesign"],
    featured: true,
  },
  {
    id: "sprite-editor",
    title: "Sprite Editor",
    source: "educational",
    categories: ["software"],   
    featured: false,
  },
  {
    id: "grading-app",
    title: "Web Grading Application",
    source: "educational",
    categories: ["webdev"],   
    featured: false,
  },
];